spring.application.name=base_team

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/team
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect